version: "2"

networks:
  app-tier:
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sage-utils-dev
    environment:
      - APP_HOST=0.0.0.0
      - APP_DEBUG=False
      - APP_SERVER=none
      - WAIT_FOR_RABBITMQ=30
    volumes:
      - ./:/app/
    depends_on:
      - rabbitmq
    networks:
      - app-tier
    tty: true

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=vhost
    networks:
      - app-tier
